[package]
name = "tokio-thread-per-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
affinity = "0.1.2"
crossbeam = "0.8.2"
libc = "0.2.126"
tokio = { version = "1.20.1", features = ["rt"] }